version: "3.3"

services:
  database:
    image: mongo:4.0.3
    container_name: mean_mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - ./mongo:/home/mongodb
      - ./mongo.docker/:/docker-entrypoint-initdb.d/
      - ./mongo/db:/data/db
    ports:
      - "${MONGO_DATABASE_PORT}:27017"
